name: CI for PR into develop

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: echo "테스트 실행!"