name: CI for PR into develop

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-tests:
    if: github.event.pull_request.head.ref != 'main' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: echo "테스트 실행!"

      - name: Print debug info
        run: |
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"